version: '3'
services:
  mysql:
    image: mysql:8.0.23
    container_name: container_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  api:
    container_name: api
    image: node:16
    restart: always
    ports:
      - 3000:3001
    environment:
      - DB_HOST=mysql
      - DB_NAME=
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_PORT=3001
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: bash
    tty: true
    stdin_open: true
    depends_on:
      - mysql